# Generated by Django 4.2.28 on 2026-02-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='periods',
            field=models.ManyToManyField(blank=True, related_name='destinations', to='destinations.historicperiod'),
        ),
    ]
