# Generated by Django 4.2.28 on 2026-02-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_historicperiod_destination_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicperiod',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
