# Generated by Django 4.2.28 on 2026-02-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_historicperiod_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicperiod',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='periods/images/'),
        ),
    ]
